image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-environment-a22
  pullPolicy: IfNotPresent
  tag: sometaghere

env:
  # ODH Core Writer Connection
  BDP_BASE_URL: http://bdp-core.core.svc.cluster.local
  BDP_PROVENANCE_NAME: 
  BDP_PROVENANCE_VERSION: 
  BDP_ORIGIN: systems
  
  LOG_LEVEL: INFO

  MQ_QUEUE: mqtt-client.parking-onstreet-merano
  MQ_EXCHANGE: routed
  MQ_KEY: mqtt-client.parking-onstreet-merano
  MQ_CLIENT: tr-parking-onstreet-merano

  RAW_DATA_BRIDGE_ENDPOINT: http://raw-data-bridge.core.svc.cluster.local:2000

  SERVICE_NAME: tr-parking-onstreet-merano
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317
  
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
  - name: ODH_TOKEN_URL
    secret: oauth-collector
    key: tokenUri
  - name: ODH_CLIENT_ID
    secret: oauth-collector
    key: clientId
  - name: ODH_CLIENT_SECRET
    secret: oauth-collector
    key: clientSecret