# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "opendatahub-collectors"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/opendatahub-collectors"

[[annotations]]
path = ["**.gitignore", ".pre-commit-config.yaml", ".github/**", ".github/workflows/***", "**/go.mod", "**/go.sum", "**/*.json", "**/*.pdf", "**/*.http", "**/*.kml", "**/*.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**helm/**.yaml", "**crawler-config/**.yaml", "**helm/**.tpl", "**helm/**/NOTES.txt", "**.helmignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"
