# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-parking-switzerland
  pullPolicy: IfNotPresent
  tag: latest

env:
  MQ_CLIENT: dc-parking-switzerland
  PROVIDER: parking-switzerland

  CRON: "0 10,40 * * * *"
  BIKE_PARKING_URL: "https://data.opentransportdata.swiss/dataset/bike-parking/resource_permalink/bike_parking.json"
  CAR_PARKING_URL: "https://data.opentransportdata.swiss/dataset/parking-facilities/resource_permalink/parking-facilities.json"
  SERVICE_NAME: dc-parking-switzerland
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
