# SPDX-FileCopyrightText: 2026 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

x-app-common:
  &app-common
  build:
    dockerfile: infrastructure/docker/Dockerfile
    context: .
    target: dev
  env_file:
    - .env
  volumes:
    - ./src:/code
    - pkg:/go/pkg/mod
  working_dir: /code

services:

  app-bdp:
    <<: *app-common
    profiles:
      - bdp
    networks:
      - ingestion

  app:
    <<: *app-common
    depends_on:
      rabbitmq:
        condition: service_healthy
    profiles:
      - dev

  rabbitmq:
    extends:
      file: ../lib/docker-compose/docker-compose.rabbitmq.yml
      service: rabbitmq
    attach: false

    profiles:
      - dev

volumes:
  pkg:

networks:
  ingestion:
    external: true
