image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/api-crawler
  pullPolicy: IfNotPresent
  tag: "0.2.0" # Set this when upgrading chart with --set-value

env:
  LOG_LEVEL: "INFO"
  MQ_CLIENT: dc-api-crawler-bike-boxes
  PROVIDER: api-crawler/bike-boxes

  CRON: "0 0/10 * * * *"
  CONFIG_PATH: "/config/config.yaml"

  SERVICE_NAME: dc-api-crawler-bike-boxes
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri

configMap:
  mountPath: "/config/"
  files: {}