{{- if .Values.envSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sftp-server.envSecretName" . }}
type: Opaque
stringData:
{{- range $k, $v := .Values.envSecret }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
