image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/dc-mqtt-client
  pullPolicy: IfNotPresent
  tag: "latest" # Set this when upgrading chart with --set-value

env:
  LOG_LEVEL: INFO
  MQTT_CLIENTID: NOI-TECHPARK-TEST
  MQTT_TOPIC: 
  MQTT_URI: ssl://prod-mqtt.systems.bz:8883
  MQ_CLIENT: dc-mqtt-client-parking-onstreet-merano
  MQ_EXCHANGE: ingress
  PROVIDER: mqtt-client/parking-onstreet-merano
envSecret:
  MQTT_PASS:
  MQTT_USER:
envSecretRef:
  - name: MQ_URI 
    secret: rabbitmq-svcbind
    key: uri
