# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: . 
    env_file:
      - .env
    volumes:
      - ./src:/code
      - pkg:/go/pkg/mod
    working_dir: /code
    network_mode: host 
    depends_on: 
      - cluster-proxy
    restart: unless-stopped


  cluster-proxy:
    image: alpine/k8s:1.31.11
    volumes:
      - ~/.kube/:/root/.kube/:r
      - ~/.aws/:/root/.aws/:r
    env_file:
      - .env
    entrypoint: >
      sh -c " \\
        kubectl port-forward --context $K8S_CONTEXT -n core svc/rabbitmq-headless --address 0.0.0.0 5672 & \\
        kubectl port-forward --context $K8S_CONTEXT -n core svc/raw-data-bridge --address 0.0.0.0 2000 & \\
        kubectl port-forward --context $K8S_CONTEXT -n core svc/bdp-core --address 0.0.0.0 8080:80 \\
      "
    healthcheck:
      test: ["CMD", "curl",  "http://localhost:8080/actuator/health"]
      interval: 2s
    network_mode: host
volumes:
  pkg:

