# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

services:
  app:
    build:
      dockerfile: infrastructure/docker/Dockerfile
      context: . 
    env_file:
      - .env
    volumes:
      - ./src:/code
      - pkg:/go/pkg/mod
    working_dir: /code
    network_mode: host 
volumes:
  pkg:

