# SPDX-FileCopyrightText: 2024 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/multi-rest-poller
  pullPolicy: IfNotPresent
  tag: "0.2.0"

env:
  MQ_CLIENT: dc-multi-rest-poller-emobility-ch
  PROVIDER: multi-rest-poller/emobility-ch
  CRON: "0 */5 * * * *"
  HTTP_CONFIG_PATH: "/config/http-config.yaml"
  SERVICE_NAME: dc-multi-rest-poller-emobility-ch
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri

configMap:
  mountPath: "/config/"
  files: {}