image:
  repository: ghcr.io/noi-techpark/opendatahub-collectors/tr-gtfs-to-trip
  pullPolicy: IfNotPresent

env:
  LOG_LEVEL: INFO

  SOURCE: skyalps
  TRIP_TAGS: "trip:flight"
  
  # content writer
  ODH_CORE_URL: https://api.tourism.testingmachine.eu/v1
  ODH_CORE_TOKEN_URL: https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/token

  MQ_QUEUE: tr-gtfs-to-trip-skyalps
  MQ_EXCHANGE: transformed
  MQ_KEY: gtfs-api.skyalps.#
  MQ_CLIENT: tr-gtfs-to-trip-skyalps

  RAW_DATA_BRIDGE_ENDPOINT: "http://raw-data-bridge.core.svc.cluster.local:2000"

  SERVICE_NAME: tr-gtfs-to-trip-skyalps
  TELEMETRY_TRACE_GRPC_ENDPOINT: tempo-distributor-discovery.monitoring.svc.cluster.local:4317

envSecret:
  ODH_CORE_TOKEN_CLIENT_ID: ""
  ODH_CORE_TOKEN_CLIENT_SECRET: ""

envSecretRef:
  - name: MQ_URI
    secret: rabbitmq-svcbind
    key: uri
