name: CI/CD dc-api-crawler-bike-boxes

on: 
  push:
    paths:
      - "collectors/api-crawler/**"
      - "!collectors/api-crawler/infrastructure/helm/*"
      - "collectors/api-crawler/infrastructure/helm/bike-boxes.*.yaml"
      - "collectors/api-crawler/infrastructure/crawler-config/bike-boxes.yaml"
      - ".github/workflows/dc-api-crawler-bike-boxes.yml"

env:
  WORKING_DIRECTORY: collectors/api-crawler
  HTTP_CONFIG_PATH: infrastructure/crawler-config/bike-boxes.silky.yaml
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/dc-api-crawler
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector
  K8S_NAME: dc-api-crawler-bike-boxes

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency: dc-api-crawler-bike-boxes-build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}

  deploy-bike-boxes-test:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev/crawlerv1'
    needs: build
    runs-on: ubuntu-24.04
    concurrency: dc-api-crawler-bike-boxes-test
    environment: test
    env:
      VALUES_YAML: infrastructure/helm/bike-boxes.test.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          # Personalize HTTP_CONFIG_PATH first
          yq -i '.auth.clientId = "${{ secrets.BIKE_BOXES_CLIENT_ID }}"' "${{ env.HTTP_CONFIG_PATH }}"
          yq -i '.auth.clientSecret = "${{ secrets.BIKE_BOXES_CLIENT_SECRET }}"' "${{ env.HTTP_CONFIG_PATH }}"

          yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML}}
          yq -i '.image.tag="${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.pullPolicy="IfNotPresent"' ${{ env.VALUES_YAML }}
          yq -i '.configMap.files["config.yaml"] = load_str("${{ env.HTTP_CONFIG_PATH }}")' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: dc-api-crawler-bike-boxes
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY}}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1
    
  deploy-bike-boxes-prod:
    if: github.ref == 'refs/heads/prod'
    needs: build
    runs-on: ubuntu-24.04
    concurrency: dc-api-crawler-bike-boxes-prod
    environment: prod
    env:
      VALUES_YAML: infrastructure/helm/bike-boxes.prod.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          # Personalize HTTP_CONFIG_PATH first
          yq -i '.auth.clientId = "${{ secrets.BIKE_BOXES_CLIENT_ID }}"' "${{ env.HTTP_CONFIG_PATH }}"
          yq -i '.auth.clientSecret = "${{ secrets.BIKE_BOXES_CLIENT_SECRET }}"' "${{ env.HTTP_CONFIG_PATH }}"
          
          yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML}}
          yq -i '.image.tag="${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.pullPolicy="IfNotPresent"' ${{ env.VALUES_YAML }}
          yq -i '.configMap.files["config.yaml"] = load_str("${{ env.HTTP_CONFIG_PATH }}")' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: dc-api-crawler-bike-boxes
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY}}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1