name: CI/CD dc-sftp-server-skyalps

on: 
  push:
    paths:
      - "collectors/sftp-server/**"
      - "!collectors/sftp-server/infrastructure/helm/*"
      - "collectors/sftp-server/infrastructure/helm/skyalps.yaml"
      - ".github/workflows/dc-sftp-server-skyalps.yml"

env:
  WORKING_DIRECTORY: collectors/sftp-server
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/dc-sftp-server
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector
  VALUES_YAML: infrastructure/helm/skyalps.yaml
  K8S_NAME: dc-sftp-server-skyalps

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency: dc-sftp-server-skyalps-build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}

  deploy-skyalps-test:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feat/sftp-server'
    needs: build
    runs-on: ubuntu-24.04
    concurrency: dc-sftp-server-skyalps-test
    environment: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env: 
          # must be passed this way + strenv, else the special characters within the secret are interpreted
          SSH_KEY_ED25519: ${{secrets.SFTP_SKYALPS_PRIVATE_KEY_ED25519}}
          SSH_KEY_RSA: ${{secrets.SFTP_SKYALPS_PRIVATE_KEY_RSA}}
        run: |
          yq -i '.image.repository="${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML}}
          yq -i '.image.tag="${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
          yq -i '.image.pullPolicy="IfNotPresent"' ${{ env.VALUES_YAML }}

          yq -i '.envSecret.SFTP_PASS="${{secrets.SFTP_SKYALPS_PASSWORD}}"' ${{ env.VALUES_YAML }}
          yq -i '.envSecret.SSH_KEY_ED25519 = strenv(SSH_KEY_ED25519)' ${{ env.VALUES_YAML }}
          yq -i '.envSecret.SSH_KEY_RSA = strenv(SSH_KEY_RSA)' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: dc-sftp-server-skyalps
          k8s-namespace: collector
          chart-path: ${{ env.WORKING_DIRECTORY}}/infrastructure/helm/sftp-server
          values-file: ${{ env.WORKING_DIRECTORY}}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1