# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

name: CI/CD tr-bike-ecocounter

on: 
  push:
    paths:
      - "transformers/bike-ecocounter/**"
      - ".github/workflows/tr-bike-ecocounter.yml"     

env:
  PROJECT_NAME: tr-bike-ecocounter
  WORKING_DIRECTORY: transformers/bike-ecocounter
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/tr-bike-ecocounter
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector

jobs:
  tests:
    runs-on: ubuntu-24.04
    concurrency: tr-bike-ecocounter-tests
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Run tests
        run: docker run --rm --volume ./src:/code --volume ./resources:/resources --volume ./testdata:/testdata $(docker build -q . -f infrastructure/docker/Dockerfile --target test)
        working-directory: ${{env.WORKING_DIRECTORY}}

  build:
    runs-on: ubuntu-24.04
    concurrency: tr-bike-ecocounter-build
    needs: 
      - tests
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}
          
  deploy-test:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feat/bike-ecounter'
    needs: 
      - build
    runs-on: ubuntu-24.04
    concurrency: tr-bike-ecocounter-deploy-test
    environment: test
    env:
      VALUES_YAML: infrastructure/helm/values.test.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
            yq -i '.image.repository = "${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML }}
            yq -i '.image.tag = "${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
            yq -i '.image.pullPolicy = "IfNotPresent"' ${{ env.VALUES_YAML }}      
            yq -i '.env.BDP_PROVENANCE_NAME="${{ env.PROJECT_NAME }}"' ${{ env.VALUES_YAML }}      
            yq -i '.env.BDP_PROVENANCE_VERSION="${{github.sha}}"' ${{ env.VALUES_YAML }}      

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: ${{ env.KUBERNETES_NAMESPACE }}
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    needs: 
      - build
    runs-on: ubuntu-24.04
    concurrency: tr-bike-ecocounter-deploy-prod
    environment: prod
    env:
      VALUES_YAML: infrastructure/helm/values.prod.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
            yq -i '.image.repository = "${{ env.DOCKER_IMAGE }}"' ${{ env.VALUES_YAML }}
            yq -i '.image.tag = "${{ env.DOCKER_TAG }}"' ${{ env.VALUES_YAML }}
            yq -i '.image.pullPolicy = "IfNotPresent"' ${{ env.VALUES_YAML }}      
            yq -i '.env.BDP_PROVENANCE_NAME="${{ env.PROJECT_NAME }}"' ${{ env.VALUES_YAML }}      
            yq -i '.env.BDP_PROVENANCE_VERSION="${{github.sha}}"' ${{ env.VALUES_YAML }}      

      - name: Deploy on cluster  
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: ${{ env.KUBERNETES_NAMESPACE }}
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1
