name: CI/CD tr-gtfs-to-trip-skyalps

on:
  push:
    paths:
      - "transformers/gtfs-to-trip/infrastructure/**"
      - "transformers/gtfs-to-trip/src/**"
      - ".github/workflows/tr-gtfs-to-trip-skyalps.yml"

env:
  WORKING_DIRECTORY: transformers/gtfs-to-trip
  DOCKER_IMAGE: ghcr.io/noi-techpark/opendatahub-collectors/tr-gtfs-to-trip
  DOCKER_TAG: ${{ github.sha }}
  KUBERNETES_NAMESPACE: collector

jobs:
  test:
    runs-on: ubuntu-24.04
    concurrency: tr-gtfs-to-trip-skyalps-build
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Run tests
      run: docker run --rm $(docker build -q . -f infrastructure/docker/Dockerfile --target test)
      working-directory: ${{ env.WORKING_DIRECTORY }}

  build:
    runs-on: ubuntu-24.04
    concurrency: tr-gtfs-to-trip-skyalps-build
    needs:
      - test
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build and push images
      uses: noi-techpark/github-actions/docker-build-and-push@v2
      with:
        working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
        docker-username: ${{ github.actor }}
        docker-password: ${{ secrets.GITHUB_TOKEN }}

  deploy-test:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feat/tr-flights-ssim-gtfs'
    needs:
      - build
    runs-on: ubuntu-24.04
    concurrency: tr-gtfs-to-trip-skyalps-deploy-test
    environment: test
    env:
      PROJECT_NAME: tr-gtfs-to-trip-skyalps
      VALUES_YAML: infrastructure/helm/skyalps.test.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '
            .image.repository="${{ env.DOCKER_IMAGE }}" |
            .image.tag="${{ env.DOCKER_TAG }}" |
            .image.pullPolicy="IfNotPresent"
          ' ${{ env.VALUES_YAML }}

          yq -i '.envSecret.ODH_CORE_TOKEN_CLIENT_ID = "${{ secrets.CONTENT_GTFS_TO_TRIP_CLIENT_ID }}"' ${{ env.VALUES_YAML }}
          yq -i '.envSecret.ODH_CORE_TOKEN_CLIENT_SECRET = "${{ secrets.CONTENT_GTFS_TO_TRIP_CLIENT_SECRET }}"' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1

  deploy-prod:
    if: github.ref == 'refs/heads/prod'
    needs:
      - build
    runs-on: ubuntu-24.04
    concurrency: tr-gtfs-to-trip-skyalps-deploy-prod
    environment: prod
    env:
      PROJECT_NAME: tr-gtfs-to-trip-skyalps
      VALUES_YAML: infrastructure/helm/skyalps.prod.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Customize values.yaml
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          yq -i '
            .image.repository="${{ env.DOCKER_IMAGE }}" |
            .image.tag="${{ env.DOCKER_TAG }}" |
            .image.pullPolicy="IfNotPresent"
          ' ${{ env.VALUES_YAML }}

          yq -i '.envSecret.ODH_CORE_TOKEN_CLIENT_ID = "${{ secrets.CONTENT_GTFS_TO_TRIP_CLIENT_ID_PROD }}"' ${{ env.VALUES_YAML }}
          yq -i '.envSecret.ODH_CORE_TOKEN_CLIENT_SECRET = "${{ secrets.CONTENT_GTFS_TO_TRIP_CLIENT_SECRET_PROD }}"' ${{ env.VALUES_YAML }}

      - name: Deploy on cluster
        uses: noi-techpark/github-actions/helm-deploy@v2
        with:
          k8s-name: ${{ env.PROJECT_NAME }}
          k8s-namespace: collector
          chart-path: helm/generic-collector
          values-file: ${{ env.WORKING_DIRECTORY }}/${{ env.VALUES_YAML }}
          aws-access-key-id: ${{ secrets[vars.AWS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.AWS_KEY_SECRET] }}
          aws-eks-cluster-name: aws-main-eu-01
          aws-region: eu-west-1
